//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolExhibition.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMaster
    {
        public int ID { get; set; }
        public Nullable<int> ClassMasterID { get; set; }
        public Nullable<int> ExhibitionCoordinatorMasterID { get; set; }
        public string StudentName { get; set; }
    
        public virtual ClassMaster ClassMaster { get; set; }
        public virtual ExhibitionCoordinatorMaster ExhibitionCoordinatorMaster { get; set; }
    }
}
